{% set name = "dags" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dags-{{ version }}.tar.gz
  sha256: b86f890ce8b59d416f5ad95e6fb57a31e8b8d379e73d6499aa40b0287223d52e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
    - toml
  run:
    - networkx
    - python >=3.7

test:
  imports:
    - dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/dags
  summary: Tools to create executable dags from interdependent functions.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/OpenSourceEconomics/dags
  doc_url: https://dags.readthedocs.io/

extra:
  recipe-maintainers:
    - janosg
    - tobiasraabe
