{% set name = "dags" %}
{% set version = "0.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dags-{{ version }}.tar.gz
  sha256: 21e42990c655c0a73e3e07c0a7d40da7af57a22494a4713bb357c12ae50a9f85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - toml
  run:
    - networkx
    - python >={{ python_min }}
    - flatten-dict

test:
  imports:
    - dags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OpenSourceEconomics/dags
  summary: Tools to create executable dags from interdependent functions.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/OpenSourceEconomics/dags
  doc_url: https://dags.readthedocs.io/

extra:
  recipe-maintainers:
    - janosg
    - tobiasraabe
    - timmens
