{% set name = "dags" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dags-{{ version }}.tar.gz
  sha256: 6f2346933619f331efaf608086ca9264ef2b1299e95cfa674531624975a6d376

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - toml
  run:
    - networkx
    - python >={{ python_min }}

test:
  imports:
    - dags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OpenSourceEconomics/dags
  summary: Tools to create executable dags from interdependent functions.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/OpenSourceEconomics/dags
  doc_url: https://dags.readthedocs.io/

extra:
  recipe-maintainers:
    - janosg
    - tobiasraabe
